name: Build and test on macOS
on:
  workflow_call:

concurrency:
  group: "${{ github.ref }}-macos"
  cancel-in-progress: true

jobs:
  macos:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        submodules_recursive: true
    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: ~/.cache/vcpkg
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-
    - name: Setup sccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        max-size: 1000M
        variant: sccache
    - name: Setup vcpkg
      run: |
        ./vcpkg/bootstrap-vcpkg.sh
        cmake -B build -S .
        cmake --build build
    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: "macos-artifacts"
        retention-days: 28
        path: |-
          build/app/MmsTestApp